version: '2.0'
services:
  redis:
    image: redis:alpine
    container_name: pimcore-redis

  db:
    image: mariadb:10.1
    container_name: pimcore-mariadb
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
    volumes:
      - pimcore-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  adminer:
    image: adminer
    container_name: pimcore-adminer
    restart: always
    ports:
      - 8080:8080

  php:
    image: dpfaffenbauer/pimcore:PHP7.3-apache
    container_name: pimcore-php
    volumes:
      - .:/var/www/html:cached
    ports:
     - "80:80"
     - "443:443"
    links:
     - db:db
     - redis:redis

  php-debug:
    image: dpfaffenbauer/pimcore:PHP7.3-apache-debug
    container_name: pimcore-debug-php
    volumes:
      - .:/var/www/html:cached
    ports:
     - "8888:80"
    links:
     - db:db
     - redis:redis
    environment:
      - PHP_IDE_CONFIG="serverName=localhost"

volumes:
  pimcore-database:
